$ANSIBLE_VAULT;1.1;AES256
39363639393137383138653638616634646134656666363731323331653861303737653130356264
3566636266653236666439613636663730636362306234340a396162383266396234613361306335
66373465326136346332653034353137393361363135326162643031353539356465646430316235
6633313532383730330a636531373761656138613162323034653832633064356533323937636539
31303635383066363463363461323761613038316238346132316166333764373035356239393765
36326264366166366233356434336236666437363366396431663462313565343631336537303039
34623038313835646633363166643865633731313263366236373237346261646162333533613035
62623632353261613763616563373730623564356431633264653666323463613366383365306330
3833