$ANSIBLE_VAULT;1.1;AES256
34343938313030306465653439623862636433616534656538386232393538353964633038383138
6437323030616466326135303861303733323236376666310a333263323032366430343531366630
36336634633062663265323331333463616232616133346335623636343665376638363466666466
3961643362363865320a663966333339363866646565356162393631373136636630393136316235
31363865616639343036303030613561356139626233383839303136656662303030326535656431
32646164626466303861653735323937313965366165336166633435636430633933393733353034
34636234373839303962646166373262636263363139633430363365326665346638303565643161
38373162306636613464376663656635323533356131323539323338323639336461353966616538
34336533613438346131353463383261343466313534663135323335643838303063